import { Fragment, type ReactNode } from 'react'
import katex from 'katex'
import 'katex/dist/katex.min.css'

/**
 * Renders a string that may contain LaTeX math, splitting it into plain-text and
 * math segments and typesetting the math with KaTeX. Math is delimited by
 * \( … \) or $ … $ (inline) and \[ … \] or $$ … $$ (display). Everything is
 * rendered in KaTeX *inline* mode so the output nests safely inside a <p> — for
 * a large stacked fraction author it with \dfrac{…}{…}. Plain strings with no
 * delimiter take a fast path and render unchanged (so it is cheap to wrap every
 * question/option/explanation, math or not). Any KaTeX parse error falls back to
 * the raw TeX so a bad stem never blanks the screen.
 */
const MATH_RE = /\\\[([\s\S]+?)\\\]|\\\(([\s\S]+?)\\\)|\$\$([\s\S]+?)\$\$|\$([^$\n]+?)\$/g

function renderTeX(tex: string): string {
  try {
    return katex.renderToString(tex, { throwOnError: false, displayMode: false, output: 'html' })
  } catch {
    return tex
  }
}

export default function MathText({
  text,
  className,
}: {
  text?: string | null
  className?: string
}) {
  if (text == null || text === '') return null
  // Fast path: nothing that could open a math segment.
  if (!text.includes('\\') && !text.includes('$')) return <>{text}</>

  const nodes: ReactNode[] = []
  let last = 0
  let key = 0
  let m: RegExpExecArray | null
  MATH_RE.lastIndex = 0
  while ((m = MATH_RE.exec(text)) !== null) {
    if (m.index > last) nodes.push(<Fragment key={key++}>{text.slice(last, m.index)}</Fragment>)
    const tex = (m[1] ?? m[2] ?? m[3] ?? m[4] ?? '').trim()
    nodes.push(
      <span
        key={key++}
        className={className}
        // KaTeX HTML is generated by the library from our own authored TeX.
        dangerouslySetInnerHTML={{ __html: renderTeX(tex) }}
      />,
    )
    last = m.index + m[0].length
  }
  if (last < text.length) nodes.push(<Fragment key={key++}>{text.slice(last)}</Fragment>)
  return <>{nodes}</>
}
