import { Fragment, memo, type ReactNode } from 'react'
import katex from 'katex'
import 'katex/dist/katex.min.css'

/**
 * Renders a string that may contain LaTeX math, splitting it into plain-text and
 * math segments and typesetting the math with KaTeX. Math is delimited by
 * \( … \) or $ … $ (inline) and \[ … \] or $$ … $$ (display). Everything is
 * rendered in KaTeX *inline* mode so the output nests safely inside a <p> — for
 * a large stacked fraction author it with \dfrac{…}{…}. Plain strings with no
 * delimiter take a fast path and render unchanged (so it is cheap to wrap every
 * question/option/explanation, math or not). Any KaTeX parse error falls back to
 * the raw TeX so a bad stem never blanks the screen.
 */
const MATH_RE = /\\\[([\s\S]+?)\\\]|\\\(([\s\S]+?)\\\)|\$\$([\s\S]+?)\$\$|\$([^$\n]+?)\$/g

// Cache is keyed by the source TeX string alone — displayMode/output below are
// fixed constants for every call, so `tex` is the only input that affects the
// result. Never evicted: the question bank is finite per session, so this stays
// bounded in practice.
const renderCache = new Map<string, string>()

function renderTeX(tex: string): string {
  const cached = renderCache.get(tex)
  if (cached !== undefined) return cached
  let html: string
  try {
    html = katex.renderToString(tex, { throwOnError: false, displayMode: false, output: 'html' })
  } catch {
    html = tex
  }
  renderCache.set(tex, html)
  return html
}

/**
 * A single-`$…$` span is ambiguous: authored math (`$x^2$`) vs a stray pair of
 * literal dollar signs around prose ("crossed $100 billion … $102 billion"). The
 * latter is common in economy/current-affairs text, where KaTeX would typeset the
 * sentence between the two `$` as math and mangle it into unreadable italics. Real
 * math is kept (any TeX command `\`, a sub/superscript `^`/`_`, or a `{…}` group);
 * a span carrying a currency word or two+ plain words is treated as literal text.
 * (Only applied to single-`$` spans — `\(…\)`, `\[…\]`, `$$…$$` are always math.)
 */
function isLiteralDollarSpan(s: string): boolean {
  if (/[\\^_{}]/.test(s)) return false
  if (/\b(billion|million|trillion|crore|lakh)\b/i.test(s)) return true
  return (s.match(/[A-Za-z]{3,}/g) ?? []).length >= 2
}

function MathText({
  text,
  className,
}: {
  text?: string | null
  className?: string
}) {
  if (text == null || text === '') return null
  // Fast path: nothing that could open a math segment.
  if (!text.includes('\\') && !text.includes('$')) return <>{text}</>

  const nodes: ReactNode[] = []
  let last = 0
  let key = 0
  let m: RegExpExecArray | null
  MATH_RE.lastIndex = 0
  while ((m = MATH_RE.exec(text)) !== null) {
    if (m.index > last) nodes.push(<Fragment key={key++}>{text.slice(last, m.index)}</Fragment>)
    // A single-`$…$` span that is really a pair of literal dollar signs around
    // prose (currency amounts) is emitted verbatim rather than typeset.
    if (m[4] != null && isLiteralDollarSpan(m[4])) {
      nodes.push(<Fragment key={key++}>{m[0]}</Fragment>)
      last = m.index + m[0].length
      continue
    }
    const tex = (m[1] ?? m[2] ?? m[3] ?? m[4] ?? '').trim()
    nodes.push(
      <span
        key={key++}
        className={className}
        // KaTeX HTML is generated by the library from our own authored TeX.
        dangerouslySetInnerHTML={{ __html: renderTeX(tex) }}
      />,
    )
    last = m.index + m[0].length
  }
  if (last < text.length) nodes.push(<Fragment key={key++}>{text.slice(last)}</Fragment>)
  return <>{nodes}</>
}

export default memo(MathText)
