// ─── Server-driven UI: the icon allowlist ────────────────────────────────────
// A layout names an icon as a string ("flame"), and this map turns it into a
// component. Deliberately a fixed map rather than a dynamic lucide import: the
// bundler can only tree-shake what it can see, and `lucide-react[name]` would
// drag all ~1,500 icons (≈500 KB) into the app to serve a dozen banners.
//
// Every icon here is already used somewhere in the app, so adding the map costs
// nothing extra in the bundle. To offer a new one, import it and add a line —
// that is a store/OTA release, which is the honest boundary: SDUI arranges the
// pieces a build ships with.

import {
  Activity,
  AlertCircle,
  Award,
  BarChart3,
  Bell,
  BookOpen,
  Calculator,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronRight,
  ClipboardList,
  Clock,
  Compass,
  Crown,
  Download,
  FileText,
  Flame,
  Gift,
  GraduationCap,
  Heart,
  IndianRupee,
  Info,
  Layers,
  Library,
  ListChecks,
  Lock,
  MessageSquare,
  Newspaper,
  Play,
  RefreshCw,
  Rocket,
  ScrollText,
  ShieldCheck,
  Sparkles,
  Star,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  Users,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const SDUI_ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  alert: AlertCircle,
  award: Award,
  chart: BarChart3,
  bell: Bell,
  book: BookOpen,
  calculator: Calculator,
  calendar: CalendarDays,
  check: Check,
  check_circle: CheckCircle2,
  chevron: ChevronRight,
  clipboard: ClipboardList,
  clock: Clock,
  compass: Compass,
  crown: Crown,
  download: Download,
  file: FileText,
  flame: Flame,
  gift: Gift,
  graduation: GraduationCap,
  heart: Heart,
  rupee: IndianRupee,
  info: Info,
  layers: Layers,
  library: Library,
  list: ListChecks,
  lock: Lock,
  message: MessageSquare,
  news: Newspaper,
  play: Play,
  refresh: RefreshCw,
  rocket: Rocket,
  scroll: ScrollText,
  shield: ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  timer: Timer,
  trending: TrendingUp,
  trophy: Trophy,
  users: Users,
  zap: Zap,
}

/** Icon names a console author can pick from — used by the editor's dropdown. */
export const SDUI_ICON_NAMES = Object.keys(SDUI_ICONS).sort()
